### ISSUE TITLE
Добавить правило для аннотаций на primary constructor

### ISSUE THREAD

**Issue by iamworkingasrudenko** [RedMadRobot/kotlin-style-guide#1]
В раздел [Аннотации](https://github.com/RedMadRobot/kotlin-style-guide#annotation) добавить пункт о том, что аннотация, применяемая к primary конструктору, располагается на той же строке.

Пример:
```
class Example @Inject constructor() {
}
```

**Comment by samarjan92** [comment]
Сейчас правила к аннотациям никак не регулируют этот момент, но и сомневаюсь, что стоит вводить такое правило. Я ни разу не встречал что бы кто-нибудь делал переносы для аннотации primary конструктора, да и в случае нескольких аннотаций мы можем выйти за границу в 120 символов и переносы все равно делать придется.

Поэтому я не вижу необходимости вводить такое правило, может есть другие соображения?

**Comment by iamworkingasrudenko** [comment]
> Я ни разу не встречал что бы кто-нибудь делал переносы для аннотации primary конструктора
Этим человеком была я. Потом задумалась, как приятней выглядит.

Когда появляется слово `constructor`, с ним может возникнуть интуитивное желание перенести его на новую строку, и аннотацию расположить соответственно.

**Comment by Fi5t** [comment]
@xanderblinov это перебор.

**Comment by Jeevuz** [comment]
@osipxd А может закрыть эти старые исшу? Они же с 18 года без движения...
