### ISSUE TITLE
Удалить или видоизменить из блока Структура класса требование сортировки методов в порядке видимости.

### ISSUE THREAD

**Issue by Jeevuz** [RedMadRobot/kotlin-style-guide#11]
Сейчас в [разделе Структура класса](https://github.com/RedMadRobot/kotlin-style-guide/blob/master/README.md#%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%B0-%D0%BA%D0%BB%D0%B0%D1%81%D1%81%D0%B0) есть порядок методов по области видимости: 
> 6. public методы 
> 7. internal методы 
> 8. protected методы 
> 9. private методы 

Это ухудшает читаемость кода и накладывает дополнительные затраты на форматирование кода. 
Располагать публичные методы вверху полезно только для библиотек, а во внутренних классах это не несет особой пользы. А увидеть в порядке видимости можно в студии открыв окошко Structure и выбрав Sort by Visibility.

Обычно чтение класса происходит сверху вниз, поэтому удобнее располагать методы по мере использования. Если в одном методе встретился вызов другого, то он идет сразу за ним. Так не нужно листать в конец класса, чтобы увидеть этот метод. Насколько я помню, именно такой вариант советует Дядюшка Боб в книге Чистый код. 

А вот что написано про это в официальных гайдах: 
[Андроид](https://developer.android.com/kotlin/style-guide#structure): 
> What is important is that each file uses some logical order, which its maintainer could explain if asked. For example, new functions are not just habitually added to the end of the file, as that would yield “chronological by date added” ordering, which is not a logical ordering. 

[Котлин](https://kotlinlang.org/docs/coding-conventions.html#class-layout):
> Do not sort the method declarations alphabetically or by visibility, and do not separate regular methods from extension methods. Instead, put related stuff together, so that someone reading the class from top to bottom can follow the logic of what's happening. Choose an order (either higher-level stuff first, or vice versa) and stick to it.

**Comment by mrblrrd** [comment]
Если брать только пункты 6-9, то я абсолютно согласен. На мой взгляд расположение по смыслу куда более полезно. Оно в рамках одного файла помогает анализировать [связность функций между собой](https://ru.wikipedia.org/wiki/%D0%A1%D0%B2%D1%8F%D0%B7%D0%BD%D0%BE%D1%81%D1%82%D1%8C_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)), чтобы в нужный момент провести рефакторинг и легче выделить лишние для класса ответственности в делегаты.

**Comment by osipxd** [comment]
Я тоже за расположение по смыслу и согласен со всеми доводами. Но добавлю в этот тред аргументы которые при прошлом обсуждении называли против сортировки по смыслу.

1. Формализовать такую сортировку сложно, а значит ещё сложнее написать проверку для статического анализатора.
2. Вытекает из первого, что правила "расположения по смыслу" у всех в голове могут быть разные, что может стать проблемой на ревью
3. Публичные методы сверху позволяют сразу посмотреть на весь API класса

К слову, последний пункт я не считаю критичным потому что окошко Structure в этом случае спасает.

**Comment by Jeevuz** [comment]
Формализовать не сложно. Например "метод идёт следующим за тем в котором впервые упоминается". Есть ли готовые анализаторы такого  не знаю. И если у кого-то логика будет немного другая, ну и пусть. Главное, что логика.  Сейчас же мы на ревью просим друг друга двигать методы вверх вниз просто так. Ну либо анализатор просит. 

Даже если у кого-то будет самая глупая логика в мире. Какая? Я не могу придумать какая именно и чтобы она была менее логичной, чем по видимости :)))
