### ISSUE TITLE
Упростить блок про Именованные аргументы и избавиться от магического числа 3.

### ISSUE THREAD

**Issue by Jeevuz** [RedMadRobot/kotlin-style-guide#12]
В блоке про [Именованные аргументы](https://github.com/RedMadRobot/kotlin-style-guide/blob/master/README.md#%D0%B8%D0%BC%D0%B5%D0%BD%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5-%D0%B0%D1%80%D0%B3%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B) на мой взгляд слишком много завязано на количество элементов, а не на логику. 

Я бы заменил 
> Если аргументов больше 3х,то следует их именовать.

на 
> Если значение аргумента не говорит о том, что это за параметр, то следует именовать аргумент.

Потому что даже пример
```
runOperation(
    method = operation::run,
    consumer = consumer,
    errorHandler = errorHandler,
    tag = tag,
    cache = cache,
    cacheMode = cacheMode
)
```

читается хуже, чем когда по смыслу
```
runOperation(
    method = operation::run,
    consumer,
    errorHandler,
    tag,
    cache,
    cacheMode
)
```

Что-то похожее есть сейчас в той части, где про примитивы: 
> Именовать аргументы примитивных типов. При этом если аргумент один, и из контекста вызова функции **понятно для чего он нужен, то можно его не именовать.**

Правило про именование примитивов я бы убрал тоже. Не стоит основываться на том примитив ли это. Лучше всё так же на том, понятно ли по значению или имени функции, что это за параметр.

**Comment by mrblrrd** [comment]
Всеми руками за озвученную идею: основывать правила не на количественных или качественных критериях, а на семантических. Короче говоря, по смыслу все делать. 

Это, мне кажется, напрямую исходит из задачи, которую код стайл призван решить – упростить понимание кода. Если за определенными конструкциями и способами написания фиксировать четкую семантику, то при разпознавании их в тексте быстрее будет приходить понимание, что собственно хотел автор сказать.

**Comment by osipxd** [comment]
При формировании этих правил была идея сделать их такими, чтобы можно было написать автоматические проверки для статического анализатора, поэтому так много завязок на количество или какие-то жёсткие правила.
В целом, согласен что тут можно переписать правило, чтобы оно применялось по смыслу. При этом считаю, что будет полезно оставить примеры ситуаций когда мы считаем что из названия аргумента не понятна его суть:
- при передаче `null`
- при передаче строковых литералов и примитивов
- при передаче нескольких лямбд

**Comment by Jeevuz** [comment]
Null и лямбды точно хорошие правила. А вот примитивы лучше тоже по смыслу, на мой взгляд.
