### ISSUE TITLE
Возможность перемешивать переопределенные и абстрактный методы с методами класса. 

### ISSUE THREAD

**Issue by Jeevuz** [RedMadRobot/kotlin-style-guide#19]
В #13 предложена такая последовательность в [структуре класса](https://github.com/RedMadRobot/kotlin-style-guide#%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%B0-%D0%BA%D0%BB%D0%B0%D1%81%D1%81%D0%B0):
```
...
3. Абстрактные методы
4. Переопределенные методы родительского класса (желательно в порядке их следования в родительском классе)
5. Реализации методов интерфейсов (желательно в порядке добавления интерфейсов в класс и следования методов в каждом интерфейсе)
6. Методы класса (в логическом порядке. Например, метод располагается после того, в котором впервые упомянут). 
...
```
Было бы хорошо также разрешить перемешивать abstract и override методы с методами класса, чтобы была единая логика относительно всех методов (например, метод располагается после того, в котором впервые упомянут). 

Считаю, что вот так: 
```kotlin
override fun onSomeActionInSuperclass() {
  doSomethingHere()
}

private fun doSomethingHere() {
  ...
}

override fun onAnotherActionInSuperclass() {
  ...
}
```
будет читаться лучше чем 
```kotlin
override fun onSomeActionInSuperclass() {
  doSomethingHere()
}

override fun onAnotherActionInSuperclass() {
  ...
}

private fun doSomethingHere() {
  ...
}

```

Что думаете?

**Comment by Zestxx** [comment]
Хочется понять на чем основано твое предположение что это  "будет читаться лучше". Можешь раскрыть свою мысль пошире? В чем проигрывает текущее решение, что выигрываем от нового?

**Comment by Jeevuz** [comment]
Будет читаться сверху вниз. Видишь использование и ищешь метод где-то ниже близко, а не через несколько методов внизу. Когда ревью делаешь (и нет возможности прыгнуть на метод) это особенно заметно.

**Comment by sonulen** [comment]
Меня единственно смущает, что теперь чтобы найти все переопределенные методы надо будет искать через поиск по override по файлу (в ситуации если класс большой)

и кажется не всегда будет лучше читаться.

пример (имхо конечно же), когда будет сложнее читать:

```kotlin
class ProfileFragment @Inject constructor(
) : BaseFragment(R.layout.0) {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        transitionSharedAxis(MaterialSharedAxis.Z)
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        viewModel.onViewCreated()

        initView()
        observeViewModel()
    }

    private fun initView() = with(binding) {
        // Много кода (40-50 строк)
    }

    private fun observeViewModel() {
        // observe
    }

    override fun onEvent(event: Event) {
        when (event) {
            is SelfEvent -> someAwesome()
            else -> super.onEvent(event)
        }
    }
}
```

**Comment by Jeevuz** [comment]
> теперь чтобы найти все переопределенные методы надо будет искать через поиск по override по файлу
Да, но вроде бы это не сложно. Все равно половину методов надо искать поиском если файл большой. 
А в какой ситуации тебе надо искать оверрайды?

**Comment by Jeevuz** [comment]
> пример (имхо конечно же), когда будет сложнее читать

А можешь уточнить почему для тебя будет сложнее читать в таком варианте?

**Comment by PilotOfSparrow** [comment]
вцелом норм. Единственное, я за то чтобы методы жизненного цикла переопределялись всегда последовательно.

````
    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        viewModel.onViewCreated()

        initView()
        observeViewModel()
    }

    private fun initView() = with(binding) {
        // Много кода (40-50 строк)
    }

    override fun onResume() ...
````

**Comment by Jeevuz** [comment]
> я за то чтобы методы жизненного цикла переопределялись всегда последовательно.

Согласен, это очень полезно. В пиаре я оставил все правила про последовательность оверрайдов (как в родителе чтобы было, а ЖЦ последовательно написаны как раз), только добавил что можно обычные методы смешивать с ними.

**Comment by sonulen** [comment]
>  А можешь уточнить почему для тебя будет сложнее читать в таком варианте?

Смущает единственное: что onEvent переопределенный, будет в самом низу файла, и с учетом  
```kotlin
   private fun initView() = with(binding) {
        // Много кода (40-50 строк)
    }
```

его сложнее будет заметить.

**Comment by Jeevuz** [comment]
@sonulen А разве тебе надо именно заметить именно переопределенные методы? 
Обычно если метод интересует, то найдем его. И при чтении подряд ты до него дойдешь тоже. Зато другие читать будет удобнее. Подряд удобнее же, чем прыгать глазами в поисках используемого где-то метода. 
Плюс, "писать методы сразу после использования" может не быть твоей логикой. Может твоя логика будет "писать методы сразу после использования, но после очень важных методов таких как onEvent(), ...". У меня же цель не заставить всех писать так именно подряд, а убрать ограничение из кодстайла, ограничивающее удобства обозначенные в оф гайдах. 
Зацени сам [пиар](https://github.com/RedMadRobot/kotlin-style-guide/pull/23), он довольно гибким описание делает.
