### ISSUE TITLE
Добавить правила использования when оператора c sealed

### ISSUE THREAD

**Issue by morkovkin** [RedMadRobot/kotlin-style-guide#2]
Добавить правила использования when. Например если он используется в таком контексте 
```Kotlin
sealed class AState {
    class Started() : AState()
    class Finished() : AState()
}
```

Если в конкретном бизнес процессе  нас интересует только состояние ```Started``` то можно опустить вторую проверку

```Kotlin
when (value) {
    is AState.Started -> {
    //.. 
    }
   //проверка Finished опущена за ненадобностью обработки
}
```
Зачем это? Мне кажется так проще дополнять возможные обработки в будущем (например если нам в этом бизнес процессе потребуется обрабатывать и Finished). Также такая конструкция оставляет вопрос конечного автомата открытым и расширяемым

PS
Думаю справедливо применить это правило только для использование с sealed  классами. Простые же выражения выносить в if блоки

```Kotlin
var a = 5
//... bad
when (a) {
    5 -> {
    //.....
    }
}
// okay

if (a==5) //..

```

**Comment by Jeevuz** [comment]
@osipxd А может закрыть эти старые исшу? Они же с 18 года без движения...
