### ISSUE TITLE
Использование условных операторов с Compose

### ISSUE THREAD

**Issue by sonulen** [RedMadRobot/kotlin-style-guide#20]
При использовании compose, часто возникают ситуации когда мы хотим прятать вьюху по какому то флагу.

Что-то в духе:
`if (isVisible) Button()`

Сейчас в style guide есть такой пункт:

> Не обрамлять if выражения в фигурные скобки только если условный оператор if помещается в одну строку.

Но так как у всех вьюх куча параметров, по style guide пример выше надо написать вот так:

```
if (isVisible) {
   Button(
    .....
   )
}
```

Есть идея разрешить в случае с компоузом делать вот так:
```
if (title != null) Text(
    text = title,
    modifier = Modifier.padding(horizontal = 32.dp),
    style = SbiTextStyles.Title,
    textAlign = TextAlign.Center,
)
```

Но если есть else - мне кажется, скобки обязательны.

**Comment by Jeevuz** [comment]
Мне кажется, что в предложенном тобой варианте визуально можно потерять важную часть, саму вьюху. Что это Text сложнее высмотреть в этом варианте
```
if (title != null) Text(
    text = title,
    modifier = Modifier.padding(horizontal = 32.dp),
    style = SbiTextStyles.Title,
    textAlign = TextAlign.Center,
)
```
И гораздо проще видеть в этом: 
```
if (title != null) {
    Text(
        text = title,
        modifier = Modifier.padding(horizontal = 32.dp),
        style = SbiTextStyles.Title,
        textAlign = TextAlign.Center,
    )
}
```
А если будет сложное условие с camelCase, то еще проще потерять: 
```
if (descriptionText.isVisible && newDescription.isNotNull()) Text(
```
Ну и к тому же исключения в виде когда без else то ок, когда с то не ок тяжело запоминаются и сложно описываются.

**Comment by sonulen** [comment]
хм, тоже верно.

желание такое возникло, т.к. делал универсальную Stub вьюху и в ней и текст и титул и картинка и кнопка (и каждой может не быть). 

и вся вьюха состоит из `if(title!=null) ` `if(image!=null)`

**Comment by Jeevuz** [comment]
Может будет полезно написать какую-то вспомогательную компоуз функцию которая будет другую функцию оборачивать, плюс условие.
