### ISSUE TITLE
Указывать размерность при объявлении константы

### ISSUE THREAD

**Issue by osipxd** [RedMadRobot/kotlin-style-guide#6]
**Мотивация:** Если не указывать размерность у константы, можно неправильно её использовать в коде или забыть конвертировать в нужный формат.

```kotlin
// Bad
const val TIMEOUT = 1000L
const val PADDING = 24

// Good
const val TIMEOUT_MILLIS = 1000L
const val PADDING_DP = 24

// Good
val TIMEOUT = 1000.milliseconds
val PADDING = 24.dp
```

**Comment by osipxd** [comment]
Test

**Comment by Jeevuz** [comment]
Хорошая рекомендация, хотя и немного кажется, что это скорее про общее отношение к коду, а не к стилю. 
Добавлю, что стоит расширить до именования вообще а не только константы. Аналогично стоит поступать с именами параметров или полей:
```
fun preferGoodNames(timeoutMillis: Long)
val defaultTimeoutMillis get() = ...
```

Но кажется что в стайлгайде это должно быть на уровне рекомендации, а не требования. Тк далеко не везде это так нужно, где-то будет по типу понятно, где-то из контекста или имени функции.

**Comment by Jeevuz** [comment]
@osipxd Может дотолкаем? Вроде лайков куча у предложения
