### ISSUE TITLE
Удалить правило про lower_snake_case для имен пакетов.

### ISSUE THREAD

**Issue by Jeevuz** [RedMadRobot/kotlin-style-guide#8]
https://github.com/RedMadRobot/kotlin-style-guide/blob/0ca19aa26863e9df9e777e8f6bec51ef4a7333a8/README.md#L35-L36

Это правило очень сильно идет в разрез с тем что написано в [Kotlin Coding Conventions](https://kotlinlang.org/docs/coding-conventions.html#naming-rules)
> Using multi-word names is generally discouraged, but if you do need to use multiple words, you can either just concatenate them together or use camel case (org.example.myProject).

и в [Android Kotlin Style Guide](https://developer.android.com/kotlin/style-guide#package_names)
> Package names are all lowercase, with consecutive words simply concatenated together (no underscores).

Предлагаю убрать это правило и всю секцию, пользоваться тем что есть в официальных гайдах.

**Comment by osipxd** [comment]
Если использовать правило из гайдов, то нужно выбрать из какого.
Когда обсуждали это правило решили, что как написано в KCC названия пакетов стараемся делать из одного слова, но если прям вообще никак не получается, то `snake_case`. Выбрали `snake_case` потому что `camelCase` в пакетах казался совсем дикостью.

Я за вариант "слеплять слова вместе, если их несколько". Если слова два, это всё ещё читаемо, а больше обычно и не бывает.

**Comment by mrblrrd** [comment]
Я тоже за джавовский вариант слеплять слова вместе, если их несколько.

**Comment by VitalyKalenikLuna** [comment]
А чем слепленные слова лучше кемелКейса? Вроде принципиальной разницы никакой, только второй вариант, на мой взгляд, читается чуть лучше

**Comment by Jeevuz** [comment]
Почему джава так рекомендовала не знаю. Наверное когда точками разделены пекеджи, то читать проще, что м если там ещё и снейки. 
some.package.name.with.additionalinfo.detected
some.package.name.with.additional_info.detected
Второй вариант как-то выбивается и как бы делит в середине и не только тот пекедж, но и всю цепочку. Думаю поэтому не рекомендуют так. Но это гипотеза.
